[#174355212] Add ability to select homepage categories
fs/communitarian-discourse-plugin pull request #35
Opened 2020-09-02 12:06 UTC by Vadim-Kurnatovskiy

[PT story](https://www.pivotaltracker.com/story/show/174355212)

2020-09-03 11:00 UTC, ShaidullinArtur requested changes

2020-09-03 11:00 UTC, ShaidullinArtur commented on assets/javascripts/discourse/controllers/home.js.es6
> +  @discourseComputed("model.categories")
@Vadim-Kurnatovskiy guest sees js error if admin choose community with some access restrictions
<img width="1433" alt="Снимок экрана 2020-09-03 в 13 58 06" src="https://user-images.githubusercontent.com/6059005/92107016-cd8fb200-eded-11ea-98d1-540888becae6.png">

<img width="848" alt="Снимок экрана 2020-09-03 в 13 59 30" src="https://user-images.githubusercontent.com/6059005/92107012-cc5e8500-eded-11ea-9096-ce7d15ca54ba.png">

2020-09-03 11:20 UTC, IlgizGilmanov commented on assets/javascripts/discourse/controllers/home.js.es6
> +  @discourseComputed("model.categories")
Fixed it here https://github.com/fs/communitarian-discourse-plugin/pull/35/commits/b01379ef2e26e2e71e9bd75a5cb7b1da9a4c8983

2020-09-03 11:26 UTC, IlgizGilmanov commented on assets/javascripts/discourse/controllers/home.js.es6
> +  landingCategories(categories) {
Fixed work with an empty community list, and also limited it to four by default. https://github.com/fs/communitarian-discourse-plugin/pull/35/commits/b01379ef2e26e2e71e9bd75a5cb7b1da9a4c8983

2020-09-04 11:59 UTC, ShaidullinArtur approved these changes

2020-09-04 15:43 UTC, DmitryBarskov approved these changes

2020-09-08 06:59 UTC, merged