[#174804001] Copy changes
fs/communitarian-discourse-plugin pull request #67
Opened 2020-09-17 14:11 UTC by Vadim-Kurnatovskiy

[PT](https://www.pivotaltracker.com/story/show/174804001)

2020-09-17 15:55 UTC, ShaidullinArtur requested changes

2020-09-17 15:55 UTC, ShaidullinArtur commented on assets/javascripts/controllers/resolution-ui-builder.js.es6
> -  _autoCloseReminderText() {
Why you removed this text? In document we don't have a new version of the text

<img width="656" alt="Снимок экрана 2020-09-17 в 18 51 01" src="https://user-images.githubusercontent.com/6059005/93495469-d23c8600-f916-11ea-8d2c-32eb54e9daa2.png">

2020-09-18 07:11 UTC, Vadim-Kurnatovskiy commented on assets/javascripts/controllers/resolution-ui-builder.js.es6
> -  _autoCloseReminderText() {
We need only "Resolution active during 1 week after reopening" message.

2020-09-18 14:50 UTC, DmitryBarskov approved these changes

2020-09-18 14:50 UTC, DmitryBarskov commented on config/locales/server.en.yml
>        in the same topic.
```suggestion
      in the same dialogue.
```
My bad :)

2020-09-18 14:50 UTC, DmitryBarskov commented on config/locales/server.en.yml
>        same topic.
```suggestion
      same dialogue.
```

2020-09-18 14:50 UTC, DmitryBarskov commented on config/locales/server.en.yml
>      user_topics: Latest dialogs by @%{username}
Missed this one.
```suggestion
    user_topics: Latest dialogues by @%{username}
```

2020-09-18 14:50 UTC, DmitryBarskov commented on config/locales/server.en.yml
>          also be allowed to access the parent category. The following groups have access
```suggestion
        also be allowed to access the parent community. The following groups have access
```

2020-09-18 14:50 UTC, DmitryBarskov commented on config/locales/server.en.yml
> +    user_email_notification_topic_nil: post.dialogue is nil
I believe we have to delete logs translations.

2020-09-18 14:50 UTC, DmitryBarskov commented on config/locales/client.en.yml
>          placeholder: type the dialog title, url or id here
```suggestion
        placeholder: type the dialogue title, url or id here
```

2020-09-18 14:50 UTC, DmitryBarskov commented on config/locales/client.en.yml
>          one: there is %{count} new post in this dialog since you last read it
```suggestion
        one: there is %{count} new post in this dialogue since you last read it
```

2020-09-18 14:50 UTC, DmitryBarskov commented on config/locales/client.en.yml
>          other: there are %{count} new posts in this dialog since you last read it
```suggestion
        other: there are %{count} new posts in this dialogue since you last read it
```

2020-09-18 14:50 UTC, DmitryBarskov commented on config/locales/client.en.yml
> +      read_more_in_category: Want to read more? Browse other dialogues in %{caTlink}
```suggestion
      read_more_in_category: Want to read more? Browse other dialogues in %{catLink}
```

2020-09-18 14:50 UTC, DmitryBarskov commented on config/locales/client.en.yml
>          this topic
```suggestion
        this dialogue
```

2020-09-21 12:02 UTC, ShaidullinArtur approved these changes

2020-09-21 13:35 UTC, merged